desc "Generate HTML files"
task :html do
  `marp -w --input-dir . --output ../html`
end

desc "Start the marp server"
task :server do
  `marp -s .`
end

desc "Open the localhost page"
task :open do
  `open http://localhost:8080/`
end

task default: [:server] do
end
